#!/usr/bin/env bash
set -euo pipefail

# Research Digest Generator
# Fetches latest AI news from multiple sources and compiles a digest
# Usage: digest.sh [--output dir] [--days 1]
#
# Requires: curl, jq

OUTPUT_DIR="${HOME}/workspace/research"
DAYS=1

while [[ $# -gt 0 ]]; do
  case $1 in
    --output) OUTPUT_DIR="$2"; shift 2 ;;
    --days) DAYS="$2"; shift 2 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

mkdir -p "$OUTPUT_DIR"
DATE=$(date +%Y-%m-%d)
DIGEST_FILE="${OUTPUT_DIR}/digest-${DATE}.md"
SINCE=$(date -d "${DAYS} days ago" +%s 2>/dev/null || date -v-${DAYS}d +%s)

echo "# AI Research Digest - ${DATE}" > "$DIGEST_FILE"
echo "" >> "$DIGEST_FILE"
echo "Auto-generated at $(date -u +%H:%M) UTC" >> "$DIGEST_FILE"
echo "" >> "$DIGEST_FILE"

# --- HackerNews ---
echo "Scanning HackerNews..."
echo "## HackerNews Top Stories" >> "$DIGEST_FILE"
echo "" >> "$DIGEST_FILE"

HN_RESPONSE=$(curl -s "https://hn.algolia.com/api/v1/search?query=AI+agents+OR+LLM+OR+coding+AI&tags=story&numericFilters=created_at_i>${SINCE},points>5&hitsPerPage=10" 2>/dev/null || echo '{"hits":[]}')

echo "$HN_RESPONSE" | jq -r '.hits[] | "- [\(.title)](\(.url // "https://news.ycombinator.com/item?id=\(.objectID)")) - \(.points) points"' >> "$DIGEST_FILE" 2>/dev/null || echo "- (No results or API error)" >> "$DIGEST_FILE"
echo "" >> "$DIGEST_FILE"

# --- GitHub Trending ---
echo "Scanning GitHub Trending..."
echo "## GitHub Trending" >> "$DIGEST_FILE"
echo "" >> "$DIGEST_FILE"
echo "(Use web_fetch on https://github.com/trending for full results)" >> "$DIGEST_FILE"
echo "" >> "$DIGEST_FILE"

# --- Summary ---
echo "## Next Steps" >> "$DIGEST_FILE"
echo "" >> "$DIGEST_FILE"
echo "1. Review stories above for actionable insights" >> "$DIGEST_FILE"
echo "2. Deep-dive into promising tools with \`web_fetch\`" >> "$DIGEST_FILE"
echo "3. Submit proposals for improvements to our system" >> "$DIGEST_FILE"
echo "" >> "$DIGEST_FILE"
echo "---" >> "$DIGEST_FILE"
echo "*Generated by research-scout*" >> "$DIGEST_FILE"

echo "Digest saved: ${DIGEST_FILE}"
